# Generated by Django 5.1.6 on 2025-02-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_user_employee_user_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user_account',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
